### ISSUE TITLE
Full Text Search on all ebooks

### ISSUE THREAD

**Issue by brightinnovator** [plateaukao/epub_content_search_plugin#1]
Hi,

Does it searches the text in all the ebooks or just one ebook?

If only one, it would be great if searches the given keyword in all the ebooks

Thanks

**Comment by plateaukao** [comment]
it searches all books. :)

**Comment by brightinnovator** [comment]
The plugin is not visible

Downloaded: https://www.fosshub.com/Calibre.html?dwl=calibre-portable-installer-5.14.0.exe

Can you please attach few screenshots of installation and icon and how does it works?

Also, how to install the epub text search plugin is not clear

I tried Preferences - Plugins - Load Plugin from file

I tried both - placing the file in the plugins folder as well as loading the pluging from file...Both are failed..

Can you please test and let me know

**Comment by plateaukao** [comment]
Do you have any failure error message?

After plugin installation, you have to add the icon (action) into tool bar from Preference. And the, it will be displayed on toolbar.

<img width="400" alt="image" src="https://user-images.githubusercontent.com/4084738/115059836-b1262d00-9f19-11eb-83d1-90f57a9539bb.png">

<img width="400" alt="image" src="https://user-images.githubusercontent.com/4084738/115059879-bf744900-9f19-11eb-8dc7-8fb5ca16a0f9.png">

<img width="400" alt="image" src="https://user-images.githubusercontent.com/4084738/115059935-d0bd5580-9f19-11eb-8942-a208ed248019.png">

**Comment by brightinnovator** [comment]
I downloaded this project as zip and loaded the plugin from file option and got error - 

calibre, version 5.15.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in 'C:\\Users\\admin\\Downloads\\epub_content_search_plugin-main.zip' is invalid. It does not contain a top-level __init__.py file

calibre 5.15  embedded-python: True is64bit: False
Windows-10-10.0.18362 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 3.8.5
Windows: ('10', '10.0.18362', '', 'Multiprocessor Free')
Interface language: None
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 319, in add_plugin
  File "calibre\customize\ui.py", line 477, in add_plugin
  File "calibre\customize\ui.py", line 65, in load_plugin
  File "calibre\customize\zipplugin.py", line 284, in load
  File "calibre\customize\zipplugin.py", line 379, in _locate_code
calibre.customize.InvalidPlugin: The plugin in 'C:\\Users\\admin\\Downloads\\epub_content_search_plugin-main.zip' is invalid. It does not contain a top-level __init__.py file

i tried even zip the plugin folder alone and tried to load it via load plugins from file option

**Comment by brightinnovator** [comment]
Need the plugin installation steps with screenshots after download your project as zip

**Comment by plateaukao** [comment]
Thanks for the error log. I'll look into this issue.

**Comment by brightinnovator** [comment]
@plateaukao Get a chance to look into the issue.

**Comment by plateaukao** [comment]
please wait for the weekend, or try to install it on 4.x version of calibre. 
:)

**Comment by brightinnovator** [comment]
any update @plateaukao

**Comment by plateaukao** [comment]
@brightinnovator 

Hi, please try downloading Calibre 4.x versions and try again. I verified again that it works on calibre 4.x on Mac platform.
As for Windows platform, or Calibre 5.x versions, since I don't have that environment, sorry that I can't help on this issue.

**Comment by brightinnovator** [comment]
It's simple in Mac...Install Virtual Box and Install Windows trial version and you can verify in windows...You can install any windows version in virtual box...After identifying the issue and fix the code you can un-install the virtual box..It is not going to be permanent neither going to affect your external operating system as it is going to run inside virtual box..

**Comment by plateaukao** [comment]
Sorry that I don't wanna spend time verifying the plugin on environment I don't have at hand. The reason why it's open source is that anyone can try to modify it to fit their own needs. According to the error log, I believe it's because you installed calibre 5.x and it uses python3, which is different than the python veriosn I used(python2). That's why it fails at installation. So, please try install calibre 4.x. I think it's much simpler than installing Vortualbox, and download windows trial and verify the scenario. As you said, all the installation is simple, but it takes time. If it still has some issues for you, maybe you have to find other plugins that works on your environment directly. :)
